### ISSUE TITLE
[linalg] cling xtensor dot product results inconsistent with numpy - `nan`'s

### ISSUE THREAD

**Issue by OneRaynyDay** [QuantStack/xtensor-blas#75] opened 2018-07-31 23:54 UTC
```
import sklearn
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets
logistic = linear_model.LogisticRegression()
digits = datasets.load_digits()
X_digits = digits.data.astype(int)
y_digits = digits.target.astype(int)
logistic.fit(X_digits, y_digits)

with open("weights.npy", "ab") as f:
    np.save(f, logistic.coef_)
with open("coefs.npy", "ab") as f:
    np.save(f, logistic.intercept_)
with open("mnist.npy", "ab") as f:
    np.save(f, X_digits)

print(X_digits.dot(logistic.coef_.T))
```

Yields:

```
[[ 16.04425395 -24.57188278 -18.99064139 ... -12.53595987  -6.59369383
   -8.84759654]
 [-39.86667809   9.89095239 -21.03906964 ... -29.23834092  -4.68151324
  -19.8681834 ]
 [-24.13828765  -2.48055447   8.55444032 ... -34.4661001    0.46635158
  -26.19119682]
 ...
 [-26.91305732  -5.43773514 -19.43945597 ... -34.21642645   8.02700404
  -21.49129071]
 [ -7.463867    -9.234329   -25.17197869 ... -26.92164295  -1.00534219
   12.71348187]
 [-25.10017597 -11.51306815 -20.65175452 ... -40.86844194   5.43239693
  -10.62263562]]
```

After deserializing the matrix and doing dot products on it in xtensor:

```
#include <iostream>
#include <xtensor/xarray.hpp>
#include <xtensor/xio.hpp>
#include <xtensor/xview.hpp>
#include <xtensor/xexpression.hpp>
#include <xtensor/xnpy.hpp>

#include <xtensor-blas/xlinalg.hpp>
xt::xarray<double> x = xt::load_npy<double>("mnist.npy");
xt::xarray<double> w = xt::load_npy<double>("weights.npy");
xt::xarray<double> b = xt::load_npy<double>("coefs.npy");

std::cout << xt::linalg::dot(x, xt::transpose(w));
```

yields:

```
{{ 16.044265, -24.571906, -18.990706, ..., -12.53596 ,  -6.593694,  -8.847597},
 {-39.866668,   9.890924, -21.039149, ..., -29.238341,  -4.681513, -19.868183},
 {-24.138276,  -2.480522,   8.554367, ..., -34.4661  ,   0.466352, -26.191197},
 ..., 
 {-26.913044,        nan, -19.439551, ..., -34.216426,   8.027004, -21.491291},
 { -7.463854,  -9.234249, -25.172056, ..., -26.921643,        nan,  12.713482},
 {       nan,        nan, -20.651845, ..., -40.868442,   5.432397,        nan}}
```

Which has the same floating point values in most, but contains `nan` in some fields which are likely due to floating point overflow or underflow (can't be divide by 0).

Environment info:

```
(cling) ❯ brew list | grep blas
openblas
```

```
(cling) ❯ conda list | grep xtensor
xtensor                   0.16.4                        0    QuantStack
xtensor-blas              0.11.1          blas_openblash2d50403_0  [blas_openblas]  conda-forge
```

Using `OSX v10.13.6 High Sierra`.

**Comment by wolfv** [comment] 2018-08-02 21:44
This seems to be a really weird issue. Luckily, so far I could only reproduce it in the jupyter notebook.

Using this code:

```
template <class C>
auto countnan(const C& c)
{
    int i = 0;
    for (auto& el : c)
    {
        if (std::isnan(el))
        {
             i += 1;
        }
    }
    return i;
}
```

I was able to observe a very random nondeterministic number of nans in the result.

I wonder if this is somehow related to cling.

**Comment by wolfv** [comment] 2018-08-11 12:00
Okay, I took a second look into it.

We do import the blas libraries for cling, but we do not define `HAVE_CBLAS 1` (e.g.

```
#define HAVE_CBLAS 1
```

If you define this at the top of your notebook, you should not see any nan's anymore (at least that was the case for me).

Now that hints at a problem in the generic implementation of the dot product in FLENS.

I am looking at the output from running with `CXXBLAS_DEBUG 1` and I see that `CXXBLAS: dotu_generic` is getting called. I'll take a look if I can find something obvious.

**Comment by wolfv** [comment] 2018-08-11 12:28
Ok, i found the root cause of the issue in this line of FLENS

```
for (IndexType i=0, iY=0; i<m; ++i, iY+=incY) {
    VY y_;
    dotu_generic(n, A+i*ldA, IndexType(1), x, incX, y_);
    y[iY] += alpha * y_;
}
```

The problem is that it's `+=` assigning to potentially unitialized memory ... and that produces random nan's! 

Let's check what the BLAS manual says.

**Closed** 2018-08-11 18:57 UTC
