### ISSUE TITLE
get_leading_stride() is too restrictive

### ISSUE THREAD

**Issue by ukoethe** [QuantStack/xtensor-blas#61] opened 2018-03-13 17:26 UTC
I tried to do the following:
```
xtensor<double, 1> A{1, 2, 3, 4, 5}, 
                   B{0.25, 0.5, 0.25}, 
                   C(B.shape(), 0);

// create a view to A looking like
//    1, 2, 3,
//    2, 3, 4,
//    3, 4, 5
static_shape<std::size_t, 2> shape{3, 3}, strides{1, 1};
auto A_as_matrix = adapt(&A(0), 9, no_ownership(), shape, strides);

// call matrix multiplication
C = linalg::dot(A_as_matrix, B);
```
but got the error message "No valid layout chosen." from `get_leading_stride()` (xblas_utils.hpp, line 118). However, when I hard-wired `get_leading_stride()` to return 1, I got the desired result, so my general idea seems to be valid. How can this be solved?

**Comment by wolfv** [comment] 2018-03-13 18:24
Hi Ullrich! 

Hmm, this is a good question. Maybe, if no static layout is chosen, we should look for the smallest stride and use that as leading stride ..?

Do you think that is appropriate?

The other way to go might be to use the xarray/xtensor_adaptor directly, and choose a static layout. (However, your strides do not suggest a valid static layout).

**Comment by wolfv** [comment] 2018-03-13 18:38
If you agree with the mentioned PR, we can merge and release a new version by tomorrow.

**Comment by ukoethe** [comment] 2018-03-13 18:48
Thanks for the PR. It appears to solve my problem, but I don't know if it has any undesired side effects, as I haven't checked what exactly `get_leading_stride()` is used for.

**Comment by wolfv** [comment] 2018-03-13 18:53
get leading stride is a rather simple function: for row-major, it selects the last stride, for col-major it selects the first stride. 

Now, without a layout (e.g. custom strides), it becomes a little trickier. Either we throw an error (like before this PR), or we try to guess the best stride (with the new PR).

Other option would be to call "raw" BLAS functions ...

**Comment by ukoethe** [comment] 2018-03-13 18:56
Ok, if you don't see a failure case the solution is good.

**Comment by wolfv** [comment] 2018-03-13 19:03
Ah, actually, I need to review what I did tomorrow morning. Not sure anymore if we're looking for the smallest or the largest stride :) 
But we'll fix it first thing tomorrow

**Comment by ukoethe** [comment] 2018-03-13 19:05
Great.

**Comment by wolfv** [comment] 2018-03-13 19:54
Hi Ullrich, 

The problem is that adapt choses Dynamic Layout and in xtensor blas we require a static layout (row or col major).

If you would use the

**Comment by wolfv** [comment] 2018-03-13 19:54
Sry

**Comment by ukoethe** [comment] 2018-03-13 20:03
Your last comment gut truncated.

I also tried to pass row_major as a template   parameter, but then the code refused to apply my custom strides. I didn't find another possibility to force my matrix view to be considered row_major.

**Comment by ukoethe** [comment] 2018-03-13 21:21
Just to clarify: The view should preferrably be interpreted as row_major.

**Comment by wolfv** [comment] 2018-08-11 19:36
I think I've commented on this somewhere else before but the biggest issue with this is that BLAS is not guaranteed / does not work with such a striding scheme as the (e.g. intel) docs state:

```
lda : Specifies the leading dimension of a as declared in the calling (sub)program.
    For Layout = CblasColMajor, the value of lda must be at least max(1, m).
    For Layout = CblasRowMajor, the value of lda must be at least max(1, n).
```

so a stride smaller than the shape is not allowed, and the BLAS subroutine returns a negative info value.

It appears to be working in FLENS though -- however, that is a simpler and slower BLAS implementation.
I am going to close this issue for now.

**Closed by wolfv** 2018-08-11 19:36 UTC
